In [2]:
import numpy as np

In [26]:
# Load the data from the CSV file
fileName = "Three_SalesData.csv"
data = np.genfromtxt(fileName, delimiter=",", dtype=str)
data

array([['', 'Apr-18', 'May-18', 'Jun-18', 'Jul-18', 'Aug-18', 'Sep-18',
        'Oct-18', 'Nov-18', 'Dec-18', 'Jan-19', 'Feb-19', 'Mar-19'],
       ['L3', '390', '345', '379', '353', '365', '326', '363', '459',
        '539', '474', '340', '343'],
       ['L1', '392', '377', '347', '395', '330', '332', '340', '446',
        '573', '464', '223', '216'],
       ['P2', '250', '270', '300', '398', '376', '382', '306', '489',
        '552', '488', '298', '269'],
       ['N6', '460', '480', '450', '310', '392', '383', '314', '402',
        '640', '495', '215', '243'],
       ['N4', '460', '480', '450', '387', '388', '320', '337', '478',
        '676', '408', '338', '263'],
       ['B8', '470', '510', '360', '472', '423', '385', '353', '464',
        '598', '419', '459', '659']], dtype='<U6')

In [27]:
# Extract column headers
column_headers = data[0,1:]
column_headers

array(['Apr-18', 'May-18', 'Jun-18', 'Jul-18', 'Aug-18', 'Sep-18',
       'Oct-18', 'Nov-18', 'Dec-18', 'Jan-19', 'Feb-19', 'Mar-19'],
      dtype='<U6')

In [28]:
# Extract row headers
row_headers = data[1:, 0]
row_headers

array(['L3', 'L1', 'P2', 'N6', 'N4', 'B8'], dtype='<U6')

In [29]:
# Extract the numerical data and convert it to float
data_values = data[1:, 1:].astype(float)
data_values

array([[390., 345., 379., 353., 365., 326., 363., 459., 539., 474., 340.,
        343.],
       [392., 377., 347., 395., 330., 332., 340., 446., 573., 464., 223.,
        216.],
       [250., 270., 300., 398., 376., 382., 306., 489., 552., 488., 298.,
        269.],
       [460., 480., 450., 310., 392., 383., 314., 402., 640., 495., 215.,
        243.],
       [460., 480., 450., 387., 388., 320., 337., 478., 676., 408., 338.,
        263.],
       [470., 510., 360., 472., 423., 385., 353., 464., 598., 419., 459.,
        659.]])

### 1. All the sales for the second quarter (Jul-18 to Sep-18 inclusive), calculating the total and the mean for each month.

In [30]:
# Define the months for the second quarter
second_quarter_months = ['Jul-18', 'Aug-18', 'Sep-18']

# Find the indices of these months in the column headers
month_indices = [np.where(column_headers == month)[0][0] for month in second_quarter_months]
month_indices

[3, 4, 5]

In [31]:
# Extract the sales data from these months
second_quarter_sales = data_values[:, month_indices] # column 3, 4, 5
second_quarter_sales

array([[353., 365., 326.],
       [395., 330., 332.],
       [398., 376., 382.],
       [310., 392., 383.],
       [387., 388., 320.],
       [472., 423., 385.]])

In [32]:
# Calculate the total and mean for each month
total_sales_per_month = np.sum(second_quarter_sales, axis=0)
mean_sales_per_month = np.mean(second_quarter_sales, axis=0)

print("total_sales_per_month: ")
print(total_sales_per_month)

print("")
print("mean_sales_per_month: ")
print(mean_sales_per_month)

total_sales_per_month: 
[2315. 2274. 2128.]

mean_sales_per_month: 
[385.83333333 379.         354.66666667]


In [33]:
# Display the results
for i, month in enumerate(second_quarter_months): # enumerate is used to add index number to i
    print("-"*40)
    print(f"Month: {month}")
    print(f"Total Sales: {total_sales_per_month[i]}")
    print(f"Average Sales: {mean_sales_per_month[i]}") 
    

----------------------------------------
Month: Jul-18
Total Sales: 2315.0
Average Sales: 385.8333333333333
----------------------------------------
Month: Aug-18
Total Sales: 2274.0
Average Sales: 379.0
----------------------------------------
Month: Sep-18
Total Sales: 2128.0
Average Sales: 354.6666666666667


### 2. All the sales for stores L3 and L1, for the first and third quarter, calculating the total and mean for each quarter for each store.

In [39]:
# Define the stores and quarters
stores = ["L3", "L1"]
first_quarter_months = ['Apr-18', 'May-18', 'Jun-18']
third_quarter_months = ['Oct-18', 'Nov-18', 'Dec-18']

In [40]:
# Find store indices
store_indices = [np.where(row_headers == store)[0][0] for store in stores]
store_indices

[0, 1]

In [42]:
# Find month indices for each quarter
first_quarter_indices = [np.where(column_headers == month)[0][0] for month in first_quarter_months]
third_quarter_indices = [np.where(column_headers == month)[0][0] for month in third_quarter_months]
print(f"First quarter indices: {first_quarter_indices}")
print(f"Third quarter indices: {third_quarter_indices}")

First quarter indices: [0, 1, 2]
Third quarter indices: [6, 7, 8]


In [45]:
# Prepare a dictionary to store results
results = {}
for store, store_idx in zip(stores, store_indices):
    results[store] = {}
    # Extract sales data for the first quarter
    first_quarter_sales = data_values[store_idx, first_quarter_indices]
    total_first_quarter = np.sum(first_quarter_sales)
    mean_first_quarter = np.mean(first_quarter_sales)
    
    # Extract sales data for the third quarter
    third_quarter_sales = data_values[store_idx, third_quarter_indices]
    total_third_quarter = np.sum(third_quarter_sales)
    mean_third_quarter = np.mean(third_quarter_sales)
    
    # Store the results
    results[store]['First Quarter'] = {
        'Total': total_first_quarter,
        'Mean': mean_first_quarter
    }
    results[store]['Third Quarter'] = {
        'Total': total_third_quarter,
        'Mean': mean_third_quarter
    }


In [46]:
# Display the results
for store in results:
    print(f"Store: {store}")
    for quarter in results[store]:
        print(f"  {quarter}:")
        print(f"    Total Sales: {results[store][quarter]['Total']}")
        print(f"    Mean Sales: {results[store][quarter]['Mean']}")
    print("---------------------------")

Store: L3
  First Quarter:
    Total Sales: 1114.0
    Mean Sales: 371.3333333333333
  Third Quarter:
    Total Sales: 1361.0
    Mean Sales: 453.6666666666667
---------------------------
Store: L1
  First Quarter:
    Total Sales: 1116.0
    Mean Sales: 372.0
  Third Quarter:
    Total Sales: 1359.0
    Mean Sales: 453.0
---------------------------


### 3. All the sales for N6 and N4 that are lower than 400 and list the months in which they occur.

In [48]:
# Define the stores
stores = ['N6', 'N4']

# Find store indices
store_indices = [np.where(row_headers == store)[0][0] for store in stores]
store_indices

[3, 4]

In [49]:
for store, store_idx in zip(stores, store_indices):
    # Extract sales data for the store
    sales_data = data_values[store_idx, :]
    
    # Find indices where sales are less than 400
    low_sales_indices = np.where(sales_data < 400)[0]
    
    # Get the corresponding months
    low_sales_months = column_headers[low_sales_indices]
    low_sales_values = sales_data[low_sales_indices]
    
    # Display the results
    print(f"Store: {store}")
    for month, sale in zip(low_sales_months, low_sales_values):
        print(f"  Month: {month}, Sales: {sale}")
    if len(low_sales_months) == 0:
        print("  No sales lower than 400.")
    print("---------------------------")

Store: N6
  Month: Jul-18, Sales: 310.0
  Month: Aug-18, Sales: 392.0
  Month: Sep-18, Sales: 383.0
  Month: Oct-18, Sales: 314.0
  Month: Feb-19, Sales: 215.0
  Month: Mar-19, Sales: 243.0
---------------------------
Store: N4
  Month: Jul-18, Sales: 387.0
  Month: Aug-18, Sales: 388.0
  Month: Sep-18, Sales: 320.0
  Month: Oct-18, Sales: 337.0
  Month: Feb-19, Sales: 338.0
  Month: Mar-19, Sales: 263.0
---------------------------


## EOF