In [1]:
import numpy as np

In [9]:
# Generate a 2D array with 10,000 random numbers
random_array = np.random.rand(100, 100) # Create a 100x100 array, which has 10,000 elements.
print("The random array: ") 
print(random_array)

The random array: 
[[0.85944406 0.38395669 0.48328177 ... 0.84380736 0.82784867 0.12676501]
 [0.06571031 0.16473683 0.73290514 ... 0.96252457 0.79483036 0.90078123]
 [0.5683299  0.36154228 0.85169267 ... 0.95113415 0.20956985 0.15613233]
 ...
 [0.61267913 0.35593377 0.51522406 ... 0.16827966 0.23123354 0.05209559]
 [0.53298793 0.26038127 0.81894272 ... 0.09990872 0.68477709 0.98885147]
 [0.47295154 0.00652617 0.39393081 ... 0.31886414 0.14715263 0.39269817]]


In [10]:
# Calculate the square root of each value in the array
sqrt_array = np.sqrt(random_array)
print("The square root of random array: ")
print(sqrt_array)

The square root of random array: 
[[0.92706206 0.61964239 0.6951847  ... 0.91858987 0.90986189 0.35604074]
 [0.25634023 0.40587785 0.85609879 ... 0.98108336 0.89153259 0.94909495]
 [0.75387658 0.60128386 0.92287197 ... 0.97526107 0.45778799 0.39513584]
 ...
 [0.78273823 0.59660185 0.7177911  ... 0.41021904 0.48086748 0.22824459]
 [0.73006022 0.51027568 0.90495454 ... 0.3160834  0.82751259 0.99441011]
 [0.68771472 0.08078472 0.62763907 ... 0.56468057 0.38360478 0.62665634]]


In [7]:
# Sum all the square root values
total_sum = np.sum(sqrt_array)
print("The sum of square roots of all elements: ", total_sum)

The sum of square roots of all elements:  6633.655377383929
