In [1]:
import numpy as np

In [2]:
fileName = "Two_RandomeValues.csv"

In [3]:
# Read csv using Numpy
data_array = np.loadtxt(fileName, delimiter=",")
data_array

array([[ 68.,  54.,  95.,  65.,  68.,   6.,  50.,  63.,  99.,  81.,  14.],
       [  5.,  85.,  83.,  22.,  39.,  26.,  73.,  77.,  97.,  75.,  33.],
       [  1.,  46.,  39.,  53.,  67.,  19.,  87.,   3.,  84.,  58.,  26.],
       [ 83.,  81.,  31.,  96.,  13.,   3.,  58.,  32., 100., 100.,  96.],
       [ 71.,   2.,  63.,  84.,  85.,   5.,  67.,  35.,  76.,  77.,  76.],
       [ 79.,  67.,  44., 100.,  89.,  71.,  27.,  46.,  45.,  13.,  32.],
       [100.,  27.,  23.,  76.,  53.,  86.,   2.,  59.,  30.,  52.,   2.],
       [ 37.,  43.,  10.,  16.,  77.,  40.,  62.,   4.,  22.,  64.,  15.],
       [ 97.,  61.,   8.,  99.,  67.,  42.,  59.,   7.,  86.,  42.,  21.],
       [ 80.,  93.,  76.,  46.,  46.,  35.,  57.,  70.,  93.,  36.,  86.],
       [ 25.,  23.,  89.,  58.,  89.,  52.,  21.,  65.,  52.,  25.,  45.]])

In [4]:
# Extract rows (5, 7, 9)
rows_5_7_9 = data_array[[5,7,9], :]
rows_5_7_9

array([[ 79.,  67.,  44., 100.,  89.,  71.,  27.,  46.,  45.,  13.,  32.],
       [ 37.,  43.,  10.,  16.,  77.,  40.,  62.,   4.,  22.,  64.,  15.],
       [ 80.,  93.,  76.,  46.,  46.,  35.,  57.,  70.,  93.,  36.,  86.]])

In [6]:
# Extract columns (0, 7, 10)
columns_0_7_10 = data_array[:, [0, 7, 10]]
columns_0_7_10

array([[ 68.,  63.,  14.],
       [  5.,  77.,  33.],
       [  1.,   3.,  26.],
       [ 83.,  32.,  96.],
       [ 71.,  35.,  76.],
       [ 79.,  46.,  32.],
       [100.,  59.,   2.],
       [ 37.,   4.,  15.],
       [ 97.,   7.,  21.],
       [ 80.,  70.,  86.],
       [ 25.,  65.,  45.]])

In [10]:
# Extract data from rows (7 to 10) and columns (1 to 3)
extractedData = data_array[7:11, 1:4] # Note: The end of each data does not mean including data
extractedData

array([[43., 10., 16.],
       [61.,  8., 99.],
       [93., 76., 46.],
       [23., 89., 58.]])